### ISSUE TITLE
Error With Ajax on Mobile Pack

### ISSUE THREAD

**Issue by faizytech** [appticles/wordpress-mobile-pack#34]
I am using Store Locator Plugin on the Website.
When i load the page on desktop. all the functionality of the store locator is working fine.
but when i open same page from wordpress mobile pack it is not showing listing that came from ajax. It Shows Wordpress backend in response of ajax.
Page is https://centracare.org/florida/locations/

kindly help me out 
I will be waiting for your response

**Comment by anghelalexandra** [comment]
Hi there,

Please add support requests by using the chat from [wpmobilepack.com](https://wpmobilepack.com) or opening a ticket on the [support forum](https://wordpress.org/support/plugin/wordpress-mobile-pack).

For future references, I'll also add a reply here. The [mobile app theme](https://github.com/appticles/pwa-theme-obliq) is an Angular JS / Ionic app that is not compatible with these types of widgets. The Store Locator Plugin is inserting its html code and styles directly in the page (which works fine on a responsive theme), but the JavaScript code will not be executed by the mobile app which is also JavaScript based.

The only solution in such cases is to use iframes - expose the widget's contents on a separate url and add the iframe code in the mobile app's content.
