### ISSUE TITLE
H5P plugin compatibility with WP Mobile Pack

### ISSUE THREAD

**Issue by DelphyB** [appticles/wordpress-mobile-pack#49]
Hi,
We're testing WP Mobile Pack for some courses online to increase learning purpose for our students. You can watch an example here : http://histologie.univ-nantes.fr. We're using H5P plugin for interactive content. It's very powerful and supposed to be already REST API. Nevertheless it doesn't work with WP Mobile Pack. Happen to know why?

Thank you in advance for any help.

**Comment by DelphyB** [comment]
Thank you Alexandra,
Well... I'll search another plugin then to replace H5P because we want to test WP Mobile Pack for now. I'll tell you ;)

**Comment by anghelalexandra** [comment]
Alright, thanks :)
